name: Docker

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - uses: docker/setup-buildx-action@v2
    - name: Build and push 1.26 image
      uses: docker/build-push-action@v4
      with:
        context: build
        platforms: linux/amd64,linux/arm64
        file: build/Dockerfile.alpine
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:1.26.2-alpine,${{ env.REGISTRY }}/${{ github.repository }}:1.26-alpine
        build-args: |
          NGINX_VERSION=1.26.2
    - name: Build and push 1.27 image
      uses: docker/build-push-action@v4
      with:
        context: build
        platforms: linux/amd64,linux/arm64
        file: build/Dockerfile.alpine
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:1.27.3-alpine,${{ env.REGISTRY }}/${{ github.repository }}:1.27-alpine
        build-args: |
          NGINX_VERSION=1.27.3
